#!/bin/bash

ssh_hardening() {
    cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup

    sed -i 's/^#\?Port.*/Port 2222/' /etc/ssh/sshd_config
    sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
    sed -i 's/^#\?MaxAuthTries.*/MaxAuthTries 3/' /etc/ssh/sshd_config
    sed -i 's/^#\?MaxSessions.*/MaxSessions 2/' /etc/ssh/sshd_config
    sed -i 's/^#\?X11Forwarding.*/X11Forwarding no/' /etc/ssh/sshd_config
    sed -i 's/^#\?AllowAgentForwarding.*/AllowAgentForwarding no/' /etc/ssh/sshd_config
    sed -i 's/^#\?AllowTcpForwarding.*/AllowTcpForwarding no/' /etc/ssh/sshd_config
    sed -i 's/^#\?ClientAliveInterval.*/ClientAliveInterval 300/' /etc/ssh/sshd_config
    sed -i 's/^#\?ClientAliveCountMax.*/ClientAliveCountMax 2/' /etc/ssh/sshd_config
    sed -i 's/^#\?TCPKeepAlive.*/TCPKeepAlive no/' /etc/ssh/sshd_config
    sed -i 's/^#\?LogLevel.*/LogLevel VERBOSE/' /etc/ssh/sshd_config

    sshd -t

    systemctl reload ssh
}

firewall_hardening() {
    apt install ufw -y
    sudo ufw --force reset
    ufw default deny incoming
    ufw default allow outgoing
    ufw allow 2222/tcp
    ufw logging on
    ufw --force enable
    ufw status verbose
}

dns_hardening() {
    cat > /etc/resolv.conf << 'EOF'
# Generated by dhcpcd from ens33.dhcp
# /etc/resolv.conf.head can replace this line
domain localdomain
nameserver 192.168.93.2
nameserver 8.8.8.8
# /etc/resolv.conf.tail can replace this line
EOF

chattr -i /etc/resolv.conf
}

grub_hardening() {
    local password="debian13"
    cat > /etc/grub.d/40_custom << EOF
#!/bin/sh
exec tail -n +3 \$0

set superusers="grubadmin"
password_pbkdf2 grubadmin $(echo -e "$password\n$password" | grub-mkpasswd-pbkdf2 | awk '/grub.pbkdf2/{print $NF}')
EOF

    chmod +x /etc/grub.d/40_custom
    update-grub
}

security_packages() {
    apt update && apt install fail2ban debsums apt-listbugs needrestart rkhunter auditd
}

kernel_hardening() {
    cat > /etc/sysctl.d/99-custom.conf << EOF
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.all.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv4.tcp_syncookies = 1
net.ipv4.conf.all.log_martians = 1
EOF

sysctl -p /etc/sysctl.d/99-custom.conf
}

fail2ban_hardening() {
    apt update && apt install fail2ban
    cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
}

suggestions() {
    apt update && apt install libpam-tmpdir
    grep tmpdir /etc/pam.d/common-session

}

while true; do
    echo ""
    echo "1) ssh_hardening"
    echo "2) firewall_hardening"
    echo "3) dns_hardening"
    echo "4) grub_hardening"
    echo "5) security_packages"
    echo "6) kernel_hardening"
    echo "7) fail2ban_hardening"
    echo "8) suggestions"

    read -p "option: " option
    case $option in
    1)
        ssh_hardening
        ;;
    2)
        firewall_hardening
        ;;
    3)
        dns_hardening
        ;;
    4)
        grub_hardening
        ;;
    5)
        security_packages
        ;;
    6)
        kernel_hardening
        ;;
    7)
        fail2ban_hardening
        ;;
    8)
        suggestions
        ;;
    esac
done